### ISSUE TITLE
Unable to Access EJ data from CGS Quilt

### ISSUE THREAD

**Issue by preetijuturu** [preetijuturu/p280s21project3#12]
Error message: "No Credentials Error"

**Comment by knaaptime** [comment]
is this on your local machine or the cgshub?

**Comment by lsala010** [comment]
this is on the cgshub

**Comment by knaaptime** [comment]
i'll work on it (it has something to do with a package conflict on the server). In the meantime, you could use this code to download a version onto the server

```python
import quilt3
b = quilt3.Bucket("s3://spatial-ucr")
b.fetch("epa/ejscreen/ejscreen_2020.parquet", "./ejscreen_2020.parquet")
```
(or whatever year you're using)

then just read in the file locally when you want to use it, e.g.

```python
ej = pd.read_parquet(`ejscreen_2020.parquet')

**Comment by lsala010** [comment]
Thank you for the help, we appreciate it :)

**Comment by WawNun** [comment]
Thanks a lot, Eli !

I was able to retrieve the data using the code provide above.
The code ej = pd.read_parquet(`ejscreen_2020.parquet') line has a minor typo so please use the following
ej = pd.read_parquet('ejscreen_2020.parquet')

Also, in the class demo, we used ejscreen to label the data so make sure to recall ej instead of ejscreen.
Hope this helps!

**Comment by knaaptime** [comment]
closing issues once they're resolved is a great way to feel good about making progress on a project :)
